[package]
	categories = ["encoding", "graphics", "multimedia"]
	description = "The collage generator"
	edition = "2018"
	keywords = ["image", "graphics", "multimedia", "svg"]
	name = "collagen"
	repository = "https://github.com/rben01/collagen"
	rust-version = "1.56.0"
	version = "0.1.0"

[dependencies]
	base64 = "0.13.0"
	clap = "2.33.3"
	lazy_static = "1.4.0"
	lazycell = "1.3.0"
	quick-xml = "0.22.0"
	regex = "1.5.4"
	serde = { version = "1.0.127", features = ["derive"] }
	serde_json = "1.0.65"
	tempfile = "3.2.0"
	zip = "0.5.13"
