[package]
	edition = "2018"
	name = "collagen"
	version = "0.1.0"

[dependencies]
	base64 = "0.13.0"
	lazy_static = "1.4.0"
	lazycell = "1.3.0"
	quick-xml = "0.22.0"
	regex = "1.5.4"
	serde = { version = "1.0.127", features = ["derive", "rc"] }
	serde_json = "1.0.65"
	tempfile = "3.2.0"
	typetag = "0.1.7"
	unicode-normalization = "0.1.19"
	zip = "0.5.13"
