[package]
	categories = ["encoding", "graphics", "multimedia"]
	description = "The collage generator"
	documentation = "https://docs.rs/collagen"
	edition = "2021"
	keywords = ["image", "graphics", "multimedia", "svg"]
	license-file = "LICENSE"
	name = "collagen"
	readme = "docs/readme-docsrs.md"
	repository = "https://github.com/rben01/collagen"
	rust-version = "1.56.1"
	version = "0.4.0"

[dependencies]
	base64 = "0.21.*"
	clap = { version = "4.2.*", features = ["derive"] }
	nom = "7.1.*"
	once_cell = "1.17.*"
	quick-xml = "0.28.*"
	regex = "1.5.*"
	serde = { version = "1.0.*", features = ["derive"] }
	serde_json = "1.0.*"
	serde_test = "1.0.*"
	strum = "0.24.*"
	strum_macros = "0.24.*"
	tempfile = "3.2.*"
	zip = "0.6.*"


[features]
	_any_bundled_font = []
	bundled_fonts = ["font_impact", "_any_bundled_font"]
	font_impact = ["_any_bundled_font"]

[[bin]]
	name = "clgn"
	path = "src/main.rs"
